version: '3.5'

services:
  rest:
    container_name: rest
    restart: always
    build: .
    environment: 
      MONGODB_DATABASE: people
      MONGODB_USERNAME: peopleuser
      MONGODB_PASSWORD: peoplepass
      MONGODB_HOSTNAME: mongodb
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: always
    #command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongo_admin
      MONGO_INITDB_DATABASE: admin